# Generated Makefile
CXX = g++
CXXFLAGS = -O2 -Wall -fPIC $(shell root-config --cflags) -I/afs/cern.ch/user/a/abulla/private/LOG1/jobs/latinosRDF/2024/WW_261007_test24/run_scripts/
LDFLAGS = $(shell root-config --libs) -lTMVA -lXMLIO -I/cvmfs/sft.cern.ch/lcg/views/LCG_109a/x86_64-el9-gcc13-opt/include -L/cvmfs/sft.cern.ch/lcg/views/LCG_109a/x86_64-el9-gcc13-opt/lib -lcorrectionlib -Wl,-rpath,'$$ORIGIN:$$ORIGIN/../../'

LIB_NAME = liblibrary_utils.so

all: $(LIB_NAME) /afs/cern.ch/user/a/abulla/private/LOG1/jobs/latinosRDF/2024/WW_261007_test24/run_scripts/WZJJ_EWK/WZJJ_EWK/my_run_analysis_WZJJ_EWK_WZJJ_EWK_0 /afs/cern.ch/user/a/abulla/private/LOG1/jobs/latinosRDF/2024/WW_261007_test24/run_scripts/WZJJ_QCD/WZJJ_QCD/my_run_analysis_WZJJ_QCD_WZJJ_QCD_0 /afs/cern.ch/user/a/abulla/private/LOG1/jobs/latinosRDF/2024/WW_261007_test24/run_scripts/WZJJ_Int/WZJJ_Interference/my_run_analysis_WZJJ_Int_WZJJ_Interference_0 /afs/cern.ch/user/a/abulla/private/LOG1/jobs/latinosRDF/2024/WW_261007_test24/run_scripts/WZSJJ_EWK/WZJJ_EWK/my_run_analysis_WZSJJ_EWK_WZJJ_EWK_0 /afs/cern.ch/user/a/abulla/private/LOG1/jobs/latinosRDF/2024/WW_261007_test24/run_scripts/WZSJJ_QCD/WZJJ_QCD/my_run_analysis_WZSJJ_QCD_WZJJ_QCD_0 /afs/cern.ch/user/a/abulla/private/LOG1/jobs/latinosRDF/2024/WW_261007_test24/run_scripts/WZSJJ_QCD/WZJJ_Interference/my_run_analysis_WZSJJ_QCD_WZJJ_Interference_0

WZJJ_EWK: $(LIB_NAME) /afs/cern.ch/user/a/abulla/private/LOG1/jobs/latinosRDF/2024/WW_261007_test24/run_scripts/WZJJ_EWK/WZJJ_EWK/my_run_analysis_WZJJ_EWK_WZJJ_EWK_0

WZJJ_QCD: $(LIB_NAME) /afs/cern.ch/user/a/abulla/private/LOG1/jobs/latinosRDF/2024/WW_261007_test24/run_scripts/WZJJ_QCD/WZJJ_QCD/my_run_analysis_WZJJ_QCD_WZJJ_QCD_0

WZJJ_Int: $(LIB_NAME) /afs/cern.ch/user/a/abulla/private/LOG1/jobs/latinosRDF/2024/WW_261007_test24/run_scripts/WZJJ_Int/WZJJ_Interference/my_run_analysis_WZJJ_Int_WZJJ_Interference_0

WZSJJ_EWK: $(LIB_NAME) /afs/cern.ch/user/a/abulla/private/LOG1/jobs/latinosRDF/2024/WW_261007_test24/run_scripts/WZSJJ_EWK/WZJJ_EWK/my_run_analysis_WZSJJ_EWK_WZJJ_EWK_0

WZSJJ_QCD: $(LIB_NAME) /afs/cern.ch/user/a/abulla/private/LOG1/jobs/latinosRDF/2024/WW_261007_test24/run_scripts/WZSJJ_QCD/WZJJ_QCD/my_run_analysis_WZSJJ_QCD_WZJJ_QCD_0 /afs/cern.ch/user/a/abulla/private/LOG1/jobs/latinosRDF/2024/WW_261007_test24/run_scripts/WZSJJ_QCD/WZJJ_Interference/my_run_analysis_WZSJJ_QCD_WZJJ_Interference_0

$(LIB_NAME): /afs/cern.ch/user/a/abulla/private/LOG1/jobs/latinosRDF/2024/WW_261007_test24/run_scripts/library_utils.cpp /afs/cern.ch/user/a/abulla/private/LOG1/jobs/latinosRDF/2024/WW_261007_test24/run_scripts/library_utils.h
	$(CXX) $(CXXFLAGS) -shared -o /afs/cern.ch/user/a/abulla/private/LOG1/jobs/latinosRDF/2024/WW_261007_test24/run_scripts/$@ /afs/cern.ch/user/a/abulla/private/LOG1/jobs/latinosRDF/2024/WW_261007_test24/run_scripts/library_utils.cpp
%: %.cpp $(LIB_NAME)
	$(CXX) $(CXXFLAGS) $< -o $@ -L/afs/cern.ch/user/a/abulla/private/LOG1/jobs/latinosRDF/2024/WW_261007_test24/run_scripts/ -llibrary_utils $(LDFLAGS)

clean:
	rm -f $(LIB_NAME) /afs/cern.ch/user/a/abulla/private/LOG1/jobs/latinosRDF/2024/WW_261007_test24/run_scripts/WZJJ_EWK/WZJJ_EWK/my_run_analysis_WZJJ_EWK_WZJJ_EWK_0 /afs/cern.ch/user/a/abulla/private/LOG1/jobs/latinosRDF/2024/WW_261007_test24/run_scripts/WZJJ_QCD/WZJJ_QCD/my_run_analysis_WZJJ_QCD_WZJJ_QCD_0 /afs/cern.ch/user/a/abulla/private/LOG1/jobs/latinosRDF/2024/WW_261007_test24/run_scripts/WZJJ_Int/WZJJ_Interference/my_run_analysis_WZJJ_Int_WZJJ_Interference_0 /afs/cern.ch/user/a/abulla/private/LOG1/jobs/latinosRDF/2024/WW_261007_test24/run_scripts/WZSJJ_EWK/WZJJ_EWK/my_run_analysis_WZSJJ_EWK_WZJJ_EWK_0 /afs/cern.ch/user/a/abulla/private/LOG1/jobs/latinosRDF/2024/WW_261007_test24/run_scripts/WZSJJ_QCD/WZJJ_QCD/my_run_analysis_WZSJJ_QCD_WZJJ_QCD_0 /afs/cern.ch/user/a/abulla/private/LOG1/jobs/latinosRDF/2024/WW_261007_test24/run_scripts/WZSJJ_QCD/WZJJ_Interference/my_run_analysis_WZSJJ_QCD_WZJJ_Interference_0
